server:
  port: 3000

db:
  url: 'mongodb+srv://abdelmaksoud:mongodb@cluster0.3zu58.mongodb.net/social'

cors:
  origin: https://resilient-boba-57a7de.netlify.app

jwt:
  expiresIn: 3600
  strategy: 'jwt'
  secret: 'jwt-secret-key'
