server:
  port: 3000

db:
  url: 'mongodb+srv://abdelmaksoud:mongodb@cluster0.3zu58.mongodb.net/social'

cors:
  # origin: https://adorable-kheer-de9249.netlify.app
  origin: http://localhost:3001

jwt:
  expiresIn: 3600
  strategy: 'jwt'
  secret: 'jwt-secret-key'
